# ARTWORK
# Secrets that can be set via files in `./secrets/*.secret`, via coommandline by `--set 'pgAdminUser=xyz,pgHost=host.com,...'` or even uncomment them in the lines below.
# pgAdminUser: ''
# pgHost: ''
# pgPort: ''
# pgPass: ''
# pgPassRO: ''
# pgPassTeam: ''
# esHost: ''
# esPort: ''
# esProto: ''
# esURL: ''
# githubOAuth: ''
# grafanaUser: ''
# grafanaPassword: ''
#
# You can skip some parts of the deployment (useful when deploying partailly again)
# skipBootstrap (will not run initial bootstrapping - creating logs and users, but you don't need to skip it - bootstrap pod detects already created resources)
# skipCrons (will not create new cronjobs, you should set it when cron jobs are already created, if you want to recreate cron jobs, delete existing ones first and do not set this flag)
# skipGrafanas (will not create Grafana deployments)
# skipPVs (will not attempt to create persistent volume claims, this is usually needed to avoid creating existing resource)
# skipProvisions (will not create provisioning pods, usually not needed, provisioning pod will detect already provisioned projects and only provision new ones)
# skipSecrets (will not attempt to create secrets, if you want to create new secrets delete current secrets first and do not set this flag)
# skipServices (will not attempt to create services (Load Balancers))
# skipNamespace (will skip devstats namespace creation)
# skipBootstrap: 1
# skipCrons: 1
# skipGrafanas: 1
# skipPVs: 1
# skipProvisions: 1
# skipSecrets: 1
# skipServices: 1
# skipNamespace: 1
#
# You can overwrite the number of CPU autodetected in each pod, setting this to 1 will make each pod single-threaded
# nCPUs: 0
#
# Other evrironment options
# bootstrapCommand: 'sleep'
# bootstrapCommandArgs:
#   - "36000"
#   - "bootarg"
# cmdDebug: 1
# debug: 1
# excludeVars: 'projects_health_partial_html'
# forceComputeAll: 1
# githubDebug: 1
# grafanaCommandArgs:
#   - "36000"
#   - arg2
# onlyMetrics: 'events,tz'
# periods: 'd7:t,m:f,q:t,y10:f'
# provisionCommand: './k8s/repos.sh'
# provisionCommand: './k8s/affs.sh'
# provisionCommand: './k8s/vars.sh'
# provisionCommand: './k8s/health.sh'
# provisionCommand: './k8s/clear_devstats_running_flag.sh'
# provisionCommand: './k8s/set_provisioned_flag.sh'
# provisionCommand: './k8s/add_metric.sh'
# provisionCommand: 'sleep'
# provisionCommandArgs:
#   - "36000"
# queryOut: 1
# reposDir: "/root/devstats_repos/"
# skipMetrics: 'users_activity,committers_cum'
# skipMetrics: 'projects_health'
# storageAccessModes: ReadWriteMany
# storageClass: efs
# syncCommandArgs:
#   - "syncarg"
affiliations: 'github_users.json'
bootstrapCommand: './k8s/deploy_all.sh'
bootstrapLDrop: ''
bootstrapNoCreate: ''
bootstrapPodName: devstats-provision-bootstrap
bootstrapRestartPolicy: Never
bootstrapUDrop: ''
companyAcq: "companies.yaml"
concurrencyPolicy: Forbid
esSecret: es-db
esBulkSize: 5000
fullnameOverride: devstats
grafanaCommand: 'grafana_start.sh'
grafanaImage: 'lukaszgryglicki/devstats-grafana'
grafanaNReplicas: 2
grafanaPodName: devstats-grafana
grafanaPort: 3000
grafanaRestartPolicy: Always
grafanaSecret: grafana-secret
imagePullPolicy: Always
indexCronsFrom: 0
indexCronsTo: 100
indexGrafanasFrom: 0
indexGrafanasTo: 100
indexProvisionsFrom: 0
indexProvisionsTo: 100
indexPVsFrom: 0
indexPVsTo: 100
indexServicesFrom: 0
indexServicesTo: 100
limitsBootstrapCPU: '2000m'
limitsBootstrapMemory: '2Gi'
limitsCronsCPU: '6000m'
limitsCronsMemory: '16Gi'
limitsGrafanasCPU: '2000m'
limitsGrafanasMemory: '8Gi'
limitsProvisionsCPU: '8000m'
limitsProvisionsMemory: '24Gi'
name: devstats
namespace: devstats
nameOverride: devstats
oauthSecret: github-oauth
pgSecret: pg-db
proivisionImage: 'lukaszgryglicki/devstats'
projectsFile: 'k8s/projects.yaml'
provisionCommand: './k8s/deploy_all.sh'
provisionPodName: devstats-provision
provisionRestartPolicy: Never
pvName: devstats-pvc
requestsBootstrapCPU: '200m'
requestsBootstrapMemory: '512Mi'
requestsCronsCPU: '500m'
requestsCronsMemory: '2Gi'
requestsGrafanasCPU: '300m'
requestsGrafanasMemory: '512Mi'
requestsProvisionsCPU: '500m'
requestsProvisionsMemory: '2Gi'
secretType: Opaque
servicePodName: devstats-service
serviceType: LoadBalancer
storageAccessModes: ReadWriteOnce
storageClass: gp2
skipTemp: 1
syncCommand: devstats
syncImage: 'lukaszgryglicki/devstats-minimal'
syncPodName: devstats
syncRestartPolicy: Never
volumeMountName: data
volumeMountPath: '/root'
volumeName: data
useES: 1
useESRaw: 1
useFlags: ''
useBootstrapResourcesLimits: 1
useCronsResourcesLimits: 1
useGrafanasResourcesLimits: 1
useProvisionsResourcesLimits: 1
waitForBootstrap: 30
labels:
  name: devstats
nodeSelector:
  lfda: devstats
projects:
  - proj: iovisor
    db: iovisor
    icon: 'cncf'
    org: 'IO Visor'
    repo: 'iovisor/bcc'
    cron: '5 * * * *'
    disk: 3Gi
    i: 0
  - proj: mininet
    db: mininet
    icon: 'cncf'
    org: 'Mininet'
    repo: 'mininet/mininet'
    cron: '5 * * * *'
    disk: 3Gi
    i: 1
  - proj: opennetworkinglab
    db: opennetworkinglab
    icon: 'cncf'
    org: 'Open Networking Laboratory'
    repo: 'opennetworkinglab/onos'
    cron: '6 * * * *'
    disk: 5Gi
    i: 2
  - proj: opensecuritycontroller
    db: opensecuritycontroller
    icon: 'cncf'
    org: 'Open Security Controller'
    repo: 'opensecuritycontroller/ocs-core'
    cron: '6 * * * *'
    disk: 3Gi
    i: 3
  - proj: openswitch
    db: openswitch
    icon: 'cncf'
    org: 'OpenSwitch'
    repo: 'open-switch/opx-nas-interface'
    cron: '7 * * * *'
    disk: 4Gi
    i: 4
  - proj: p4lang
    db: p4lang
    icon: 'cncf'
    org: 'P4 Language'
    repo: 'p4lang/p4c'
    cron: '7 * * * *'
    disk: 5Gi
    i: 5
  - proj: openbmp
    db: openbmp
    icon: 'cncf'
    org: 'OpenBMP'
    repo: 'OpenBMP/openbmp'
    cron: '8 * * * *'
    disk: 3Gi
    i: 6
  - proj: tungstenfabric
    db: tungstenfabric
    icon: 'cncf'
    org: 'Tungsten Fabric'
    repo: 'tungstenfabric/website'
    cron: '8 * * * *'
    disk: 3Gi
    i: 7
  - proj: cord
    db: cord
    icon: 'cncf'
    org: 'CORD'
    repo: 'opencord/voltha'
    cron: '9 * * * *'
    disk: 3Gi
    i: 8
  - proj: envoy
    db: envoy
    icon: 'envoy'
    org: 'Envoy'
    repo: 'envoyproxy/envoy'
    cron: '9 * * * *'
    disk: 4Gi
    i: 9
  - proj: zephyr
    db: zephyr
    icon: 'cncf'
    org: 'Zephyr'
    repo: 'zephyrproject-rtos/zephyr'
    cron: '11 * * * *'
    disk: 8Gi
    i: 10
  - proj: linux
    db: linux
    icon: 'cncf'
    org: 'Linux'
    repo: 'torvalds/linux'
    cron: '12 * * * *'
    disk: 10Gi
    i: 11
  - proj: kubernetes
    db: gha
    icon: 'k8s'
    org: 'Kubernetes'
    repo: 'kubernetes/kubernetes'
    cron: '13 * * * *'
    disk: 50Gi
    i: 12
  - proj: prometheus
    db: prometheus
    icon: 'prometheus'
    org: 'Prometheus'
    repo: 'prometheus/prometheus'
    cron: '18 * * * *'
    disk: 5Gi
    i: 13
  - proj: opentracing
    db: opentracing
    icon: 'opentracing'
    org: 'OpenTracing'
    repo: 'opentracing/opentracing-go'
    cron: '20 * * * *'
    disk: 3Gi
    i: 14
  - proj: fluentd
    db: fluentd
    icon: 'fluentd'
    org: 'Fluentd'
    repo: 'fluent/fluentd'
    cron: '21 * * * *'
    disk: 4Gi
    i: 15
  - proj: linkerd
    db: linkerd
    icon: 'linkerd'
    org: 'Linkerd'
    repo: 'linkerd/linkerd'
    cron: '22 * * * *'
    disk: 4Gi
    i: 16
  - proj: grpc
    db: grpc
    icon: 'grpc'
    org: 'gRPC'
    repo: 'grpc/grpc'
    cron: '23 * * * *'
    disk: 4Gi
    i: 17
  - proj: coredns
    db: coredns
    icon: 'coredns'
    org: 'CoreDNS'
    repo: 'coredns/coredns'
    cron: '25 * * * *'
    disk: 4Gi
    i: 18
  - proj: containerd
    db: containerd
    icon: 'containerd'
    org: 'containerd'
    repo: 'containerd/containerd'
    cron: '26 * * * *'
    disk: 3Gi
    i: 19
  - proj: rkt
    db: rkt
    icon: 'rkt'
    org: 'rkt'
    repo: 'rkt/rkt'
    cron: '26 * * * *'
    disk: 3Gi
    i: 20
  - proj: cni
    db: cni
    icon: 'cni'
    org: 'CNI'
    repo: 'containernetworking/cni'
    cron: '27 * * * *'
    disk: 3Gi
    i: 21
  - proj: jaeger
    db: jaeger
    icon: 'jaeger'
    org: 'Jaeger'
    repo: 'jaegertracing/jaeger'
    cron: '28 * * * *'
    disk: 4Gi
    i: 22
  - proj: notary
    db: notary
    icon: 'notary'
    org: 'Notary'
    repo: 'theupdateframework/notary'
    cron: '29 * * * *'
    disk: 3Gi
    i: 23
  - proj: tuf
    db: tuf
    icon: 'tuf'
    org: 'TUF'
    repo: 'theupdateframework/tuf'
    cron: '29 * * * *'
    disk: 3Gi
    i: 24
  - proj: rook
    db: rook
    icon: 'rook'
    org: 'Rook'
    repo: 'rook/rook'
    cron: '31 * * * *'
    disk: 4Gi
    i: 25
  - proj: vitess
    db: vitess
    icon: 'vitess'
    org: 'Vitess'
    repo: 'vitessio/vitess'
    cron: '31 * * * *'
    disk: 5Gi
    i: 26
  - proj: nats
    db: nats
    icon: 'nats'
    org: 'NATS'
    repo: 'nats-io/gnatsd'
    cron: '32 * * * *'
    disk: 5Gi
    i: 27
  - proj: opa
    db: opa
    icon: 'opa'
    org: 'OPA'
    repo: 'open-policy-agent/opa'
    cron: '32 * * * *'
    disk: 5Gi
    i: 28
  - proj: spiffe
    db: spiffe
    icon: 'spiffe'
    org: 'SPIFFE'
    repo: 'spiffe/spiffe'
    cron: '33 * * * *'
    disk: 4Gi
    i: 29
  - proj: spire
    db: spire
    icon: 'spire'
    org: 'SPIRE'
    repo: 'spiffe/spire'
    cron: '33 * * * *'
    disk: 3Gi
    i: 30
  - proj: cloudevents
    db: cloudevents
    icon: 'cloudevents'
    org: 'CloudEvents'
    repo: 'cloudevents/spec'
    cron: '33 * * * *'
    disk: 3Gi
    i: 31
  - proj: telepresence
    db: telepresence
    icon: 'telepresence'
    org: 'Telepresence'
    repo: 'telepresenceio/telepresence'
    cron: '34 * * * *'
    disk: 3Gi
    i: 32
  - proj: helm
    db: helm
    icon: 'helm'
    org: 'Helm'
    repo: 'helm/helm'
    cron: '34 * * * *'
    disk: 8Gi
    i: 33
  - proj: openmetrics
    db: openmetrics
    icon: 'openmetrics'
    org: 'OpenMetrics'
    repo: 'OpenObservability/OpenMetrics'
    cron: '36 * * * *'
    disk: 3Gi
    i: 34
  - proj: harbor
    db: harbor
    icon: 'harbor'
    org: 'Harbor'
    repo: 'goharbor/harbor'
    cron: '36 * * * *'
    disk: 4Gi
    i: 35
  - proj: etcd
    db: etcd
    icon: 'etcd'
    org: 'etcd'
    repo: 'etcd-io/etcd'
    cron: '37 * * * *'
    disk: 4Gi
    i: 36
  - proj: tikv
    db: tikv
    icon: 'tikv'
    org: 'TiKV'
    repo: 'tikv/tikv'
    cron: '38 * * * *'
    disk: 3Gi
    i: 37
  - proj: cortex
    db: cortex
    icon: 'cortex'
    org: 'Cortex'
    repo: 'cortexproject/cortex'
    cron: '38 * * * *'
    disk: 3Gi
    i: 38
  - proj: buildpacks
    db: buildpacks
    icon: 'buildpacks'
    org: 'Buildpacks'
    repo: 'buildpack/lifecycle'
    cron: '39 * * * *'
    disk: 3Gi
    i: 39
  - proj: falco
    db: falco
    icon: 'falco'
    org: 'Falco'
    repo: 'falcosecurity/falco'
    cron: '39 * * * *'
    disk: 3Gi
    i: 40
  - proj: dragonfly
    db: dragonfly
    icon: 'dragonfly'
    org: 'Dragonfly'
    repo: 'dragonflyoss/Dragonfly'
    cron: '40 * * * *'
    disk: 3Gi
    i: 41
  - proj: virtualkubelet
    db: virtualkubelet
    icon: 'virtualkubelet'
    org: 'Virtual Kubelet'
    repo: 'virtual-kubelet/virtual-kubelet'
    cron: '40 * * * *'
    disk: 3Gi
    i: 42
  - proj: cncf
    db: cncf
    icon: 'cncf'
    org: 'CNCF'
    repo: 'cncf/landscapeapp'
    cron: '41 * * * *'
    disk: 30Gi
    i: 43
  - proj: opencontainers
    db: opencontainers
    icon: 'opencontainers'
    org: 'OCI'
    repo: 'opencontainers/runc'
    cron: '41 * * * *'
    disk: 3Gi
    i: 44
  - proj: istio
    db: istio
    icon: 'cncf'
    org: 'Istio'
    repo: 'istio/istio'
    cron: '42 * * * *'
    disk: 8Gi
    i: 45
  - proj: spinnaker
    db: spinnaker
    icon: 'spinnaker'
    org: 'Spinnaker'
    repo: 'spinnaker/spinnaker'
    cron: '43 * * * *'
    disk: 4Gi
    i: 46
  - proj: knative
    db: knative
    icon: 'cncf'
    org: 'Knative'
    repo: 'knative/serving'
    cron: '44 * * * *'
    disk: 4Gi
    i: 47
  - proj: kubeedge
    db: kubeedge
    icon: 'kubeedge'
    org: 'KubeEdge'
    repo: 'kubeedge/kubeedge'
    cron: '44 * * * *'
    disk: 3Gi
    i: 48
  - proj: brigade
    db: brigade
    icon: 'brigade'
    org: 'Brigade'
    repo: 'Azure/brigade'
    cron: '45 * * * *'
    disk: 3Gi
    i: 49
  - proj: crio
    db: crio
    icon: 'crio'
    org: 'CRI-O'
    repo: 'cri-o/cri-o'
    cron: '45 * * * *'
    disk: 3Gi
    i: 50
  - proj: tekton
    db: tekton
    icon: 'tekton'
    org: 'Tekton'
    repo: 'knative/build'
    cron: '46 * * * *'
    disk: 3Gi
    i: 51
  - proj: jenkinsx
    db: jenkinsx
    icon: 'jenkinsx'
    org: 'Jenkins X'
    repo: 'jenkins-x/jx'
    cron: '46 * * * *'
    disk: 6Gi
    i: 52
  - proj: jenkins
    db: jenkins
    icon: 'jenkins'
    org: 'Jenkins'
    repo: 'jenkinsci/jenkins'
    cron: '47 * * * *'
    disk: 40Gi
    i: 53
  - proj: networkservicemesh
    db: networkservicemesh
    icon: 'networkservicemesh'
    org: 'Network Service Mesh'
    repo: 'networkservicemesh/networkservicemesh'
    cron: '48 * * * *'
    disk: 3Gi
    i: 54
  - proj: openebs
    db: openebs
    icon: 'openebs'
    org: 'OpenEBS'
    repo: 'openebs/openebs'
    cron: '48 * * * *'
    disk: 10Gi
    i: 55
  - proj: opentelemetry
    db: opentelemetry
    icon: 'opentelemetry'
    org: 'OpenTelemetry'
    repo: 'open-telemetry/opentelemetry-java'
    cron: '49 * * * *'
    disk: 3Gi
    i: 56
  - proj: graphql
    db: graphql
    icon: 'graphql'
    org: 'GraphQL'
    repo: 'graphql/graphql-js'
    cron: '50 * * * *'
    disk: 30Gi
    i: 57
  - proj: graphqljs
    db: graphqljs
    icon: 'graphqljs'
    org: 'GraphQL JavaScript'
    repo: 'graphql/graphql-js'
    cron: '51 * * * *'
    disk: 3Gi
    i: 58
  - proj: graphiql
    db: graphiql
    icon: 'graphiql'
    org: 'GraphQL IDE'
    repo: 'graphql/graphiql'
    cron: '51 * * * *'
    disk: 3Gi
    i: 59
  - proj: graphqlspec
    db: graphqlspec
    icon: 'graphqlspec'
    org: 'GraphQL Spec'
    repo: 'graphql/graphql-spec'
    cron: '51 * * * *'
    disk: 3Gi
    i: 60
  - proj: expressgraphql
    db: expressgraphql
    icon: 'expressgraphql'
    org: 'Express GraphQL'
    repo: 'graphql/express-graphql'
    cron: '51 * * * *'
    disk: 3Gi
    i: 61
